/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.blurview;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiLifecycle.OnLifecycleEvent;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.view.TiUIView;

import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.app.Activity;
import io.alterac.blurkit.BlurLayout;
import android.view.View;

@Kroll.proxy(creatableInModule=TiBlurViewModule.class)
public class BlurViewProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String LCAT = "BlurViewProxy";
	private static final boolean DBG = TiConfig.LOGD;
	BlurLayout blurLayout;
	private int blurRadius = -1;
	private float downscaleFactor = -1.0f;
	private int fps = -1;

	private class BlurView extends TiUIView
	{
		public BlurView(TiViewProxy proxy) {
			super(proxy);
			String packageName = proxy.getActivity().getPackageName();
			Resources resources = proxy.getActivity().getResources();
			View viewWrapper;

			int resId_viewHolder;
			int resIdPublish;

			resId_viewHolder = resources.getIdentifier("layout_main", "layout", packageName);
			resIdPublish = resources.getIdentifier("blurLayout", "id", packageName);

			LayoutInflater inflater = LayoutInflater.from(proxy.getActivity());
			viewWrapper = inflater.inflate(resId_viewHolder, null);
			blurLayout =  (BlurLayout) viewWrapper.findViewById(resIdPublish);

			if (blurRadius != -1) {
				blurLayout.setBlurRadius(blurRadius);
			}
			if (downscaleFactor != -1.0f) {
				blurLayout.setDownscaleFactor(downscaleFactor);
			}
			if (fps != -1) {
				blurLayout.setFPS(fps);
			}
			setNativeView(viewWrapper);
		}

		@Override
		public void processProperties(KrollDict d)
		{
			super.processProperties(d);
		}
	}


	// Constructor
	public BlurViewProxy()
	{
		super();
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		TiUIView view = new BlurView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);

		if (options.containsKey("blurFactor")) {
			blurRadius = TiConvert.toInt(options.get("blurRadius"),2);
		}
		if (options.containsKey("downscaleFactor")) {
			downscaleFactor = TiConvert.toFloat(options.get("downscaleFactor"),0.15f);
		}
		if (options.containsKey("fps")) {
			fps = TiConvert.toInt(options.get("fps"), -1);
		}
	}

	// Methods
	@Kroll.method
	public void startBlur()
	{
		blurLayout.startBlur();
		blurLayout.lockView();
	}

	// Methods
	@Kroll.method
	public void lockView()
	{
		blurLayout.lockView();
	}

	// Methods
	@Kroll.method
	public void unlockView()
	{
		blurLayout.unlockView();
	}

	// Methods
	@Kroll.method
	public void pauseBlur()
	{
		blurLayout.pauseBlur();
	}

	@Kroll.setProperty
	public void downscaleFactor(float factor){
		downscaleFactor = factor;
		blurLayout.setDownscaleFactor(factor);
	}

	@Kroll.setProperty
	public void blurRadius(int factor){
		blurRadius = factor;
		blurLayout.setBlurRadius(factor);
	}

	@Kroll.setProperty
	public void fps(int factor){
		fps = factor;
		blurLayout.setFPS(factor);
	}

	@Kroll.getProperty
	public float downscaleFactor(){
		return blurLayout.getDownscaleFactor();
	}

	@Kroll.getProperty
	public int blurRadius(){
		return blurLayout.getBlurRadius();
	}

	@Kroll.getProperty
	public int fps(){
		return blurLayout.getFPS();
	}

	@Kroll.method
	public void invalidate(){
		blurLayout.invalidate();
	}
}
