/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.blurview;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;
import android.content.res.Resources;
import android.view.LayoutInflater;
import android.app.Activity;
import io.alterac.blurkit.BlurLayout;
import android.view.View;

@Kroll.proxy(creatableInModule=TiBlurViewModule.class)
public class BlurViewProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String LCAT = "BlurViewProxy";
	private static final boolean DBG = TiConfig.LOGD;
	BlurLayout blurLayout;
	private int blurRadius = 2;
	private float downscaleFactor = 0.15f;

	private class BlurView extends TiUIView
	{
		public BlurView(TiViewProxy proxy) {
			super(proxy);
			String packageName = proxy.getActivity().getPackageName();
			Resources resources = proxy.getActivity().getResources();
			View viewWrapper;

			int resId_viewHolder;
			int resIdPublish;

			resId_viewHolder = resources.getIdentifier("layout_main", "layout", packageName);
			resIdPublish = resources.getIdentifier("blurLayout", "id", packageName);

			LayoutInflater inflater = LayoutInflater.from(proxy.getActivity());
			viewWrapper = inflater.inflate(resId_viewHolder, null);
			blurLayout =  (BlurLayout) viewWrapper.findViewById(resIdPublish);
			blurLayout.setBlurRadius(blurRadius);
			blurLayout.setDownscaleFactor(downscaleFactor);
			setNativeView(viewWrapper);
		}

		@Override
		public void processProperties(KrollDict d)
		{
			super.processProperties(d);
		}
	}


	// Constructor
	public BlurViewProxy()
	{
		super();
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		TiUIView view = new BlurView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);

		if (options.containsKey("blurFactor")) {
			blurRadius = TiConvert.toInt(options.get("blurRadius"),2);
		}
		if (options.containsKey("downscaleFactor")) {
			downscaleFactor = TiConvert.toFloat(options.get("downscaleFactor"),0.15f);
		}
	}

	// Methods
	@Kroll.method
	public void startBlur()
	{
		blurLayout.startBlur();
	}

	@Kroll.setProperty
	public void downscaleFactor(float factor){
		blurLayout.setDownscaleFactor(factor);
	}

	@Kroll.setProperty
	public void blurRadius(int factor){
		blurLayout.setBlurRadius(factor);
	}
}
